version: '3.5'
services:
  discord_bot_postgres:
    container_name: discord_bot_postgres
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres:/data/postgres
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    restart: unless-stopped

  discord_bot:
    container_name: discord_bot
    # image: discord_bot:1
    build: ./../
    depends_on:
      - discord_bot_postgres
    environment:
      DISCORD_APIKEY: {{ HERE YOUR DISCORD API KEY }}
      LOG_LEVEL: info
      CONNECTORS_DIGITALOCEAN_TIMEOUT: 2400000
      CONNECTORS_DIGITALOCEAN_TOKEN: {{ HERE YOUR DIGITAL OCEAN TOKEN }}
      CONNECTORS_CHOLLOMETRO_ENABLED: "true"
      CONNECTORS_CHOLLOMETRO_TIMEOUT: 300000
      CONNECTORS_CINESA_ENABLED: "true"
      CONNECTORS_CINESA_TIMEOUT: 600000
      CONNECTORS_ELITETORRENT_ENABLED: "true"
      CONNECTORS_ELITETORRENT_TIMEOUT: 1200000
      PGHOST: discord_bot_postgres
      PGPASSWORD: changeme
      PGUSER: postgres
      PGDATABASE: connectors
      PGPORT: 5432
    restart: always
